In [27]:
import pandas as pd
import numpy as np  

#encoding = "utf-8"
df_vendas = pd.read_csv("vendas_tech.csv", sep=",", low_memory=False)
display(df_vendas)
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")

df_gerentes['Loja'] = df_gerentes['Loja'].str.strip()
df_gerentes['Loja'] = df_gerentes['Loja'].str.title()

display(df_gerentes)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio De Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [ ]:
#inspecao
display(df_vendas)

#pega as primairas linhas
display(df_vendas.head(7))

#ultimas linhas
display(df_vendas.tail (7))

#linhas aleatorias
display(df_vendas.sample(7))

#formato da coluna
display(df_vendas.shape)

#colunas
display(df_vendas.columns)

#infos para possiveis tratamentos
display(df_vendas.info())

#descreve 
display(df_vendas.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
100093,77528,2024-03-30,São Paulo,"Monitor 27""",1200.0,3,Cliente_5144,NaN
100094,32853,2024-04-10,Salvador,Smartphone Samsung,2200.0,2,Cliente_29799,NaN
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
83142,83143,2023-01-26,Curitiba,Notebook Dell,3500.0,1,Cliente_12208,NaN
78804,78805,2024-10-10,São Paulo,Cabo HDMI,40.0,2,Cliente_1233,NaN
31998,31999,2023-11-03,São Paulo,Smartphone Samsung,2200.0,5,Cliente_16688,NaN
40427,40428,2023-11-24,Belo Horizonte,Notebook HP,3200.0,1,Cliente_6385,NaN
73829,73830,2023-06-17,São Paulo,Notebook HP,3200.0,5,Cliente_22805,NaN
9234,9235,2023-06-05,Salvador,Notebook HP,3200.0,3,Cliente_26007,NaN
80955,80956,2023-02-25,Porto Alegre,Notebook HP,3200.0,2,Cliente_17889,NaN

(100100, 8)

Index(['ID_Pedido', 'Data', 'Loja', 'Produto', 'Preco_Unitario', 'Qtd',
       'Cliente', 'Data_Base'],
      dtype='str')

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

In [ ]:
#tratamento de dados

#excluindo coluna
df_analise = df_vendas.drop(columns= ['Data_Base'])

#tratando os NaN
#df_analise = df_analise.dropna()  => exclui linhas com um ou mais NaN

#troca os valores nulos pela palavra 'online'
df_analise['Loja'] = df_analise['Loja'].fillna('Online')

#mudando o formato da data
df_analise['Data'] = pd.to_datetime(df_analise['Data'], format='%Y-%m-%d')

#padronizacao
df_analise['Loja'] = df_analise['Loja'].str.strip()
df_analise['Loja'] = df_analise['Loja'].str.title()

#remover duplicatas
df_analise = df_analise.drop_duplicates(subset=['ID_Pedido'], keep='last')

display(df_analise)
display(df_analise.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

<class 'pandas.DataFrame'>
Index: 100000 entries, 0 to 100099
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 6.1 MB

None

In [ ]:
#criar novas colunas
#faturamente
df_analise['Faturamento'] = df_analise['Qtd'] * df_analise['Preco_Unitario']

#forma de venda
df_analise['Formua de Venda'] = np.where(df_analise['Loja'] == 'Online', 'Online', 'Presencial')
                                        #np.where(condicao, se for vdd, se for falsa)

#regiao
dic_regioes = {
    'São Paulo': 'Sudeste',
    'Belo Horizonte': 'Sudeste',
    'Online': 'Online',
    'Rio De Janeiro': 'Sudeste',
    'Salvador': 'Nordeste',
    'Recife': 'Nordeste',
    'Curitiba': 'Sul',
    'Porto Alegre': 'Sul'
}

df_analise['Regiao'] = df_analise['Loja'].map(dic_regioes)
display(df_analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Formua de Venda,Regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,5500.0,Presencial,Sul
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,7000.0,Presencial,Sul
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,4400.0,Presencial,Sudeste
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,11000.0,Presencial,Nordeste
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,6400.0,Presencial,Sudeste

In [ ]:
#analise =>
#.loc
#                    [indicie, coluna]
loja = df_analise.loc[3, 'Loja']
#print(loja)

#.iloc ==> posicoes
loja = df_analise.iloc[4,4]
#print(loja)

#condicional (linha toda)
df_id_pedido_4 = df_analise[df_analise['ID_Pedido'] == 4]
#print(df_id_pedido_4)

#condicional (so um dado)
df_id_pedido_04 = df_analise[df_analise['ID_Pedido'] == 4].values[0]
#print(df_id_pedido_04)

#exportando
df_vendas_sp= df_analise[df_analise['Loja'] =='São Paulo']
df_vendas_sp.to_csv("Vendas_SP.csv")

#exportando vendas 2024
df_vendas_2024 = df_analise[df_analise['Data'].dt.year == 2024]
#condicional
df_vendas_2024 = df_analise[df_analise['Data'] >= '2024-01-01']

#dupla condicional
condicao =  df_analise['Produto'] == 'Mouse Gamer'
condicao2 =df_analise['Regiao'] == 'Sul'

df_vendas_Mouse = df_analise[condicao & condicao2]

In [ ]:
#analise por agrupamento
analise_lojas= df_analise[['Loja', 'Faturamento']].groupby('Loja', as_index=False).sum()
#colocando em ordem
analise_lojas = analise_lojas.sort_values(by='Faturamento', ascending= False)
#arrumando indicies
analise_lojas = analise_lojas.sort_index()
#arrumando o visual
analise_lojas['Faturamento'] = analise_lojas['Faturamento'].map('R${:,.2f}'.format)
#display(analise_lojas)

#rank de produto vendidos online
df_vendas_online = df_analise[df_analise['Loja'] == 'Online']

df_analise_vendas_online = df_vendas_online[['Produto','Qtd']].groupby('Produto').sum()

df_analise_vendas_online = df_analise_vendas_online.sort_values(by= 'Qtd', ascending=False)

df_analise_vendas_online= df_analise_vendas_online.rename(columns={'Qtd' : 'Vendas Totais'})
display(df_analise_vendas_online)

                    Vendas Totais
Produto
Notebook HP                   442
Cabo HDMI                     403
iPhone 14                     390
Mouse Gamer                   379
Notebook Dell                 369
Teclado Mecânico              343
Monitor 27"                   332
Smartphone Samsung            311

In [ ]:
#quais produtos venderam mais em cada loja
analise_produtos_em_lojas = df_analise[['Loja', 'Produto', 'Qtd']].groupby(['Loja', 'Produto']).sum()

#qual produto mais vendidos por loja
analise_lojas_produtos = df_analise[['Loja', 'Produto', 'Qtd']].groupby(['Produto', 'Loja']).sum()


with pd.option_context("display.max_rows", None):
    #display(analise_produtos_em_lojas)
    #display(analise_lojas_produtos)

                                    Qtd
Loja           Produto
Belo Horizonte Cabo HDMI           2636
               Monitor 27"         2625
               Mouse Gamer         2465
               Notebook Dell       2654
               Notebook HP         2775
               Smartphone Samsung  2597
               Teclado Mecânico    2609
               iPhone 14           2478
Curitiba       Cabo HDMI           2698
               Monitor 27"         2626
               Mouse Gamer         2600
               Notebook Dell       2517
               Notebook HP         2529
               Smartphone Samsung  2444
               Teclado Mecânico    2742
               iPhone 14           2652
Online         Cabo HDMI            403
               Monitor 27"          332
               Mouse Gamer          379
               Notebook Dell        369
               Notebook HP          442
               Smartphone Samsung   311
               Teclado Mecânico     343
               iPhone 14            390
Porto Alegre   Cabo HDMI           2571
               Monitor 27"         2655
               Mouse Gamer         2611
               Notebook Dell       2770
               Notebook HP         2511
               Smartphone Samsung  2603
               Teclado Mecânico    2598
               iPhone 14           2540
Recife         Cabo HDMI           2534
               Monitor 27"         2647
               Mouse Gamer         2639
               Notebook Dell       2566
               Notebook HP         2651
               Smartphone Samsung  2660
               Teclado Mecânico    2775
               iPhone 14           2652
Rio De Janeiro Cabo HDMI           2747
               Monitor 27"         2798
               Mouse Gamer         2652
               Notebook Dell       2534
               Notebook HP         2614
               Smartphone Samsung  2626
               Teclado Mecânico    2548
               iPhone 14           2702
Salvador       Cabo HDMI           2566
               Monitor 27"         2545
               Mouse Gamer         2711
               Notebook Dell       2512
               Notebook HP         2785
               Smartphone Samsung  2627
               Teclado Mecânico    2579
               iPhone 14           2671
São Paulo      Cabo HDMI           2649
               Monitor 27"         2796
               Mouse Gamer         2714
               Notebook Dell       2535
               Notebook HP         2592
               Smartphone Samsung  2476
               Teclado Mecânico    2589
               iPhone 14           2735

                                    Qtd
Produto            Loja
Cabo HDMI          Belo Horizonte  2636
                   Curitiba        2698
                   Online           403
                   Porto Alegre    2571
                   Recife          2534
                   Rio De Janeiro  2747
                   Salvador        2566
                   São Paulo       2649
Monitor 27"        Belo Horizonte  2625
                   Curitiba        2626
                   Online           332
                   Porto Alegre    2655
                   Recife          2647
                   Rio De Janeiro  2798
                   Salvador        2545
                   São Paulo       2796
Mouse Gamer        Belo Horizonte  2465
                   Curitiba        2600
                   Online           379
                   Porto Alegre    2611
                   Recife          2639
                   Rio De Janeiro  2652
                   Salvador        2711
                   São Paulo       2714
Notebook Dell      Belo Horizonte  2654
                   Curitiba        2517
                   Online           369
                   Porto Alegre    2770
                   Recife          2566
                   Rio De Janeiro  2534
                   Salvador        2512
                   São Paulo       2535
Notebook HP        Belo Horizonte  2775
                   Curitiba        2529
                   Online           442
                   Porto Alegre    2511
                   Recife          2651
                   Rio De Janeiro  2614
                   Salvador        2785
                   São Paulo       2592
Smartphone Samsung Belo Horizonte  2597
                   Curitiba        2444
                   Online           311
                   Porto Alegre    2603
                   Recife          2660
                   Rio De Janeiro  2626
                   Salvador        2627
                   São Paulo       2476
Teclado Mecânico   Belo Horizonte  2609
                   Curitiba        2742
                   Online           343
                   Porto Alegre    2598
                   Recife          2775
                   Rio De Janeiro  2548
                   Salvador        2579
                   São Paulo       2589
iPhone 14          Belo Horizonte  2478
                   Curitiba        2652
                   Online           390
                   Porto Alegre    2540
                   Recife          2652
                   Rio De Janeiro  2702
                   Salvador        2671
                   São Paulo       2735

In [29]:
#quais gerentes bateram a meta 2023
df_meta = df_analise[(df_analise['Data'].dt.year == 2023) & (df_analise['Data'].dt.month == 1)]

df_meta = df_meta[['Loja', 'Faturamento']].groupby('Loja',as_index= False).sum()

df_meta = df_meta.merge(df_gerentes, on = 'Loja', how = 'left')

df_meta['Bateu Meta'] = np.where(df_meta['Faturamento'] >= df_meta['Meta_Mensal'], 'Sim', 'Nao')
display(df_meta)

             Loja  Faturamento   Gerente  Meta_Mensal Bateu Meta
0  Belo Horizonte    1779100.0   Juliana      55000.0        Sim
1        Curitiba    1986920.0   Roberto      45000.0        Sim
2          Online     404570.0       NaN          NaN        Nao
3    Porto Alegre    1726640.0     Pedro      42000.0        Sim
4          Recife    1779020.0    Marcos      48000.0        Sim
5  Rio De Janeiro    1736830.0  Fernanda      60000.0        Sim
6        Salvador    1686070.0       Ana      52000.0        Sim
7       São Paulo    1831140.0    Carlos      50000.0        Sim